server:
  port: 7900

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekastandalone.com:7900/eureka/
  instance:
    hostname: eurekastandalone.com

management:
  endpoint:
    shutdown:
      enabled: true

spring:
  application:
    name: eureka-standalone-server-liyang
