server:
  port: 7902

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1.com:7901/eureka/
  instance:
    hostname: eureka2.com

management:
  endpoint:
    shutdown:
    enabled: true

spring:
  application:
    name: eureka-server-liyang
